# Generated by Django 5.2.5 on 2025-08-13 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('general', 'General'), ('technology', 'Technology'), ('lifestyle', 'Lifestyle'), ('travel', 'Travel'), ('food', 'Food'), ('sports', 'Sports'), ('entertainment', 'Entertainment'), ('business', 'Business'), ('education', 'Education'), ('other', 'Other')], default='general', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['author', '-created_at'], name='posts_post_author__f8ea20_idx'), models.Index(fields=['category', '-created_at'], name='posts_post_categor_bb9705_idx'), models.Index(fields=['is_active', '-created_at'], name='posts_post_is_acti_3afc54_idx')],
            },
        ),
    ]
